//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Tasler.IO.Matroska {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.matroska.org/specdata")]
    [System.Xml.Serialization.XmlRootAttribute("table", Namespace="http://www.matroska.org/specdata", IsNullable=false)]
    public partial class Table {
        
        private Element[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("element")]
        public Element[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.matroska.org/specdata")]
    public partial class Element {
        
        private System.Xml.XmlNode[] anyField;
        
        private string nameField;
        
        private int levelField;
        
        private bool levelFieldSpecified;
        
        private string idField;
        
        private ValueType typeField;
        
        private bool typeFieldSpecified;
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private bool multipleField;
        
        private bool multipleFieldSpecified;
        
        private int minverField;
        
        private bool minverFieldSpecified;
        
        private string defaultField;
        
        private bool webmField;
        
        private bool webmFieldSpecified;
        
        private string cppnameField;
        
        private string rangeField;
        
        private int bytesizeField;
        
        private bool bytesizeFieldSpecified;
        
        private string divxField;
        
        private int maxverField;
        
        private bool maxverFieldSpecified;
        
        private bool recursiveField;
        
        private bool recursiveFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandatorySpecified {
            get {
                return this.mandatoryFieldSpecified;
            }
            set {
                this.mandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool multiple {
            get {
                return this.multipleField;
            }
            set {
                this.multipleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multipleSpecified {
            get {
                return this.multipleFieldSpecified;
            }
            set {
                this.multipleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int minver {
            get {
                return this.minverField;
            }
            set {
                this.minverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minverSpecified {
            get {
                return this.minverFieldSpecified;
            }
            set {
                this.minverFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool webm {
            get {
                return this.webmField;
            }
            set {
                this.webmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool webmSpecified {
            get {
                return this.webmFieldSpecified;
            }
            set {
                this.webmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cppname {
            get {
                return this.cppnameField;
            }
            set {
                this.cppnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int bytesize {
            get {
                return this.bytesizeField;
            }
            set {
                this.bytesizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bytesizeSpecified {
            get {
                return this.bytesizeFieldSpecified;
            }
            set {
                this.bytesizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string divx {
            get {
                return this.divxField;
            }
            set {
                this.divxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxver {
            get {
                return this.maxverField;
            }
            set {
                this.maxverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxverSpecified {
            get {
                return this.maxverFieldSpecified;
            }
            set {
                this.maxverFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool recursive {
            get {
                return this.recursiveField;
            }
            set {
                this.recursiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recursiveSpecified {
            get {
                return this.recursiveFieldSpecified;
            }
            set {
                this.recursiveFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.matroska.org/specdata")]
    public enum ValueType {
        
        /// <remarks/>
        master,
        
        /// <remarks/>
        integer,
        
        /// <remarks/>
        uinteger,
        
        /// <remarks/>
        @float,
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        utf8,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        binary,
    }
}
