//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjectViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataObjectViewer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string ClipboardDisplayName {
            get {
                return ResourceManager.GetString("ClipboardDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string DeviceAspectContent {
            get {
                return ResourceManager.GetString("DeviceAspectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocPrint.
        /// </summary>
        internal static string DeviceAspectDocPrint {
            get {
                return ResourceManager.GetString("DeviceAspectDocPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string DeviceAspectIcon {
            get {
                return ResourceManager.GetString("DeviceAspectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string DeviceAspectThumbnail {
            get {
                return ResourceManager.GetString("DeviceAspectThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped Data Object.
        /// </summary>
        internal static string DroppedDataObjectBaseDisplayName {
            get {
                return ResourceManager.GetString("DroppedDataObjectBaseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Metafile.
        /// </summary>
        internal static string MediaTypeEnhancedMetafile {
            get {
                return ResourceManager.GetString("MediaTypeEnhancedMetafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MediaTypeFile {
            get {
                return ResourceManager.GetString("MediaTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDI.
        /// </summary>
        internal static string MediaTypeGDI {
            get {
                return ResourceManager.GetString("MediaTypeGDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HGLOBAL.
        /// </summary>
        internal static string MediaTypeHGLOBAL {
            get {
                return ResourceManager.GetString("MediaTypeHGLOBAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IStorage.
        /// </summary>
        internal static string MediaTypeIStorage {
            get {
                return ResourceManager.GetString("MediaTypeIStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IStream.
        /// </summary>
        internal static string MediaTypeIStream {
            get {
                return ResourceManager.GetString("MediaTypeIStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metafile Picture.
        /// </summary>
        internal static string MediaTypeMetafilePict {
            get {
                return ResourceManager.GetString("MediaTypeMetafilePict", resourceCulture);
            }
        }
    }
}
