import "StringStringPair.idl";

#define WFC Windows.Foundation.Collections

namespace MessageDialogTester
{
	[default_interface]
	runtimeclass MainPage
		: Windows.UI.Xaml.Controls.Page
		, Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		MainPage();
		MainPage ViewModel { get; };

		String Title;
		String MessageContent;

		WFC.IObservableVector<StringStringPair> QuickContentItems { get; };
		Int32 SelectedQuickContentIndex;

		Int32 SelectedButtonCountIndex;

		WFC.IObservableVector<String> DefaultButtonItems { get; };
		Int32 SelectedDefaultButtonIndex;

		WFC.IObservableVector<String> CancelButtonItems { get; };
		Int32 SelectedCancelButtonIndex;

		WFC.IObservableVector<StringStringPair> ButtonLabels { get; };
	}
}
