#define WUXD Windows.UI.Xaml.Data

namespace MessageDialogTester
{
	[default_interface]
	runtimeclass MessageDialogExceptionViewModel : WUXD.INotifyPropertyChanged
	{
		String HResultFormatted { get; };
		String Message { get; };
	}
}
